[package]
name = "mirror"
version = "0.1.0"
authors = ["Michael O'Keefe <michael.okeefe@semanticbits.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
